// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EcommerceClassDiagram;

/************************************************************/
/**
 * 
 */
public class Admistrator {
	/**
	 * 
	 */
	protected String name;
	/**
	 * 
	 */
	protected String emailAddress;
	/**
	 * 
	 */
	protected String password;
	/**
	 * 
	 */
	protected int ID;
	/**
	 * 
	 */
	boolean adminPreviliges;
	/**
	 * 
	 */
	public CustomerOrder customerorder;

	/**
	 * 
	 */
	public void addItemsInInventory() {
	}

	/**
	 * 
	 */
	public void removeProduct() {
	}

	/**
	 * 
	 */
	public void updateProduct() {
	}

	/**
	 * 
	 */
	public void updateDispatchStatus() {
	}
};
