// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EcommerceClassDiagram;

/************************************************************/
/**
 * 
 */
public class Admin extends Admistrator {
	/**
	 * 
	 */
	public int AdminID;

	/**
	 * 
	 */
	public void givePreveliges() {
	}

	/**
	 * 
	 */
	public void addUSer() {
	}

	/**
	 * 
	 */
	public void removeUser() {
	}

	/**
	 * 
	 */
	public void giveAccess() {
	}
};
