// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EcommerceClassDiagram;

/************************************************************/
/**
 * 
 */
public class Cart {
	/**
	 * 
	 */
	public String productName;
	/**
	 * 
	 */
	public int productID;
	/**
	 * 
	 */
	public int quantity;
	/**
	 * 
	 */
	public int orderNumber;
	/**
	 * 
	 */
	public CustomerOrder customer;
	/**
	 * 
	 */
	public Product product;

	/**
	 * 
	 */
	public void DisplayCart() {
	}

	/**
	 * 
	 */
	public void addItemsinCart() {
	}

	/**
	 * 
	 */
	public void updateCart() {
	}

	/**
	 * 
	 */
	public void deleteItemsinCart() {
	}
};
