// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EcommerceClassDiagram;

/************************************************************/
/**
 * 
 */
public class Customer {
	/**
	 * 
	 */
	public String CustName;
	/**
	 * 
	 */
	public String custEmailAdress;
	/**
	 * 
	 */
	public String passsword;
	/**
	 * 
	 */
	public int cutomerID;

	/**
	 * 
	 */
	public void login() {
	}

	/**
	 * 
	 */
	public void sigup() {
	}
};
