// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EcommerceClassDiagram;

/************************************************************/
/**
 * 
 */
public class CustomerOrder {
	/**
	 * 
	 */
	public int customerID;
	/**
	 * 
	 */
	public int orderNumber;
	/**
	 * 
	 */
	public char orderdate;
	/**
	 * 
	 */
	public int totalBill;
	/**
	 * 
	 */
	public String ShippingAdress;
	/**
	 * 
	 */
	public String city;
	/**
	 * 
	 */
	public String CustomerName;
	/**
	 * 
	 */
	public int PhoneNumber;
	/**
	 * 
	 */
	public boolean Dispatch;
	/**
	 * 
	 */
	public Customer customer;

	/**
	 * 
	 */
	public void showDetails() {
	}
};
