// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EcommerceClassDiagram;

/************************************************************/
/**
 * 
 */
public class inventoryManager extends Admistrator {
	/**
	 * 
	 */
	public int ManagerID;
};
