// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EcommerceClassDiagram;

/************************************************************/
/**
 * 
 */
public class Product {
	/**
	 * 
	 */
	public String itemname;
	/**
	 * 
	 */
	public float ItemPrice;
	/**
	 * 
	 */
	public int ItemID;
	/**
	 * 
	 */
	public int itemQuantity;
	/**
	 * 
	 */
	public Admistrator admistrator;
};
